#!/bin/bash

#########################################
# Got r00t o are u Amy Acker?
#########################################
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "rule-update needs root privileges or be Amy Acker.  Please try again using sudo."
    exit
fi

#########################################
# Restart NIDS processes
#########################################

# If Barnyard is enabled, restart it
if grep -i 'BARNYARD2_ENABLED="yes"' /etc/nsm/*/sensor.conf >/dev/null 2>&1; then
	echo "Restarting Barnyard2."
	/usr/sbin/nsm_sensor_ps-restart --only-barnyard2
fi

# If the IDS Engine is enabled, restart it
if grep -i 'IDS_ENGINE_ENABLED="yes"' /etc/nsm/*/sensor.conf >/dev/null 2>&1; then
	echo "Restarting IDS Engine."
	/usr/sbin/nsm_sensor_ps-restart --only-snort-alert
fi
